name: Django project test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  Test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run the docker-compose
      run: docker compose -f Docker-compose.yml up -d
    - name: Test Project
      run: docker exec backend sh -c "pytest"

  Deploy:
    name: Deploy
    needs: Test
    if: ${{ needs.Test.result == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Connect and Execute Commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd ${{ secrets.PROJECT_PATH }}
            docker-compose -f docker-compose-stage.yml stop
            git pull
            docker-compose -f docker-compose-stage.yml restart
